### ISSUE TITLE
In order to calculate forward returns with the RNN do I fit this piece of code somewhere in the notebook? `for t in [1,2,3,6,12]:

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#107]
In order to calculate forward returns with the RNN do I fit this piece of code somewhere in the notebook? `for t in [1,2,3,6,12]:
data[f'target_{t}m'] = (data.groupby(level='ticker')
[f'return_{t}m'].shift(-t))
`

Or do I need to have empty dataslots in the dataframe so that the predictions can go past the last historical date?

**Comment by cody-vandervoort** [comment]
Also out of curiosity for notebook 2 in chapter 21 i receive these error's when persisting the data `Expected binary or unicode string, got PosixPath('time_gan/experiment_00/autoencoder')` The sythetic data was still made okay was just wondering what this meant because it seemed like a big red error

**Comment by stefan-jansen** [comment]
On your first question: yes, this would be how you could compute forward returns. Pandas aligns by index, if the data that you are shifting to are not in the index, they won't be inserted. Since you're shifting back in time, this makes sense - you would otherwise have today's returns with yesterday's features at some point where today is your earliest datapoint. 

To avoid the second error, you can pass `path.as_posix()` to convert to string; you were probably passing a `pathlib` object where a string was expected.

Hope this helps.
