### ISSUE TITLE
issue when setting up new environment using yml file provided

### ISSUE THREAD

**Issue by AyEnEss** [stefan-jansen/machine-learning-for-trading#11]
Hello
I have tried to create an environment using the environment.yml file provided but I get the following error:
Solving environment: failed
ResolvePackageNotFound:
gcc_linux-64=7.2.0
binutils_impl_linux-64=2.28.1
gxx_linux-64=7.2.0
gst-plugins-base=1.14.0
gstreamer=1.14.0
gmp=6.1.2
pango=1.42.4
dbus=1.13.2
gcc_impl_linux-64=7.2.0
binutils_linux-64=7.2.0
gxx_impl_linux-64=7.2.0
ncurses=6.1
libgcc-ng=8.2.0
libstdcxx-ng=8.2.0
libuuid=1.0.3
readline=7.0
expat=2.2.6
fribidi=1.0.5
libgfortran-ng=7.3.0
graphviz=2.40.1
libedit=3.1.20170329
is there any way I can fix this? thanks for the help

**Comment by stefan-jansen** [comment]
Hi, which OS are you using? The errors refer to missing linux packages which suggests you are not using linux. There's an alternative mac_os yml file. I still need to add one for windows; this has taken a bit longer than anticipated because I don't have a Windows PC system ready for testing, unfortunately. 

As a general workaround, you can always create a virtualenv using conda, pyenv or else and just install whatever is needed for the notebooks you actually plan on running rather than a global env that contains everything for all notebooks. 

I hope this helps - please let me know if you have further questions.

**Comment by AyEnEss** [comment]
Hi @stefan-jansen 
Thanks for the response.
I am using windows so that would explain why its not working. I used [this environment.yml file](https://github.com/PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading/blob/master/environment.yml), I just assumed it was for windows since there was a seperate one for mac and linux.
in the end i just deleted the packages that couldn't be resolved from the file and then it worked fine

**Comment by stefan-jansen** [comment]
You're welcome. Packt does not update their repo regularly, so it's better to get the latest from. I've started on a second edition, so any feedback is appreciated. I hope you find the book & code examples useful!

**Comment by zhaofinance** [comment]
> Hi @stefan-jansen
> Thanks for the response.
> I am using windows so that would explain why its not working. I used [this environment.yml file](https://github.com/PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading/blob/master/environment.yml), I just assumed it was for windows since there was a seperate one for mac and linux.
> in the end i just deleted the packages that couldn't be resolved from the file and then it worked fine

It takes so much time to find the unresolved packages. Each package can be found by one time.  It seems many unresolved packages. Would you please show the resolved packages ? Thanks.

**Comment by AyEnEss** [comment]
check out my answer here 
https://github.com/stefan-jansen/machine-learning-for-trading/issues/12#issuecomment-546998908
