### ISSUE TITLE
missing ml4t-zipline from newest version of docker image

### ISSUE THREAD

**Issue by sungyunglim** [stefan-jansen/machine-learning-for-trading#114]
Hi Stefan,

I have downloaded the newest version to resolve the version issue related to tensorflow and found it works.
But this version does not seem to have "ml4t-zipline" environment and does "ml4t-backtest" instead.
I cannot run some notebook files of chapter 5 that require "ml4t-zipline".

Thanks for your help in advance.

Thanks - sungyung

**Comment by stefan-jansen** [comment]
Hi Sungyung,

I've updated the repo so that the notebooks only use the `ml4t` and `backtest` environments, which use updated libraries. I've described the changes [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation). 

Zipline only supported Python 3.5 when I published the material and Python 3.5 support has since expired but the Latest Zipline version published Oct 2020 now also supports Python3.6. I've also fixed a couple of Zipline bugs such as the need to modify the database. The current versions of the notebooks indicate where `backtest` rather than `ml4t-zipline` is needed; you should also be able to run all previous versions of the notebooks that call for `ml4t-zipline` using `backtest`.

I would recommend to update your local version of the repo using `git pull`, and please let me know if you continue to experience difficulties.

**Comment by stefan-jansen** [comment]
Please note that I just posted a new version of the image to fix a bug in the Zipline notebook 4 in chapter 4. Closing for now - feel free to reopen if you experience further issues regarding this matter.
