### ISSUE TITLE
common preprocessed dataset available ?

### ISSUE THREAD

**Issue by sungyunglim** [stefan-jansen/machine-learning-for-trading#115]
Hi Stefan,

As mentioned before, I appreciate you for writing an excellent book covering finance and machine learning. As running your scripts, I recognize the critical importance of and difficulty in collecting proper data and preprocessing them.
I guess readers may have different focuses: For me, I read your book without exercise first and now running your scripts with more focus on ML techniques and less on data preprocessing. Doing both at the same time is quite challenging and slow.
Furthermore, some APIs to get access to some sources of data do not work any longer. The present environment is different from yours.

I'm wondering whether you can share some common preprocessed dataset such as "data.h5" so that some readers including me run your scripts without data download and preprocessing. At this level, I would be happy to reproduce your results and familiarize your codes. At the next level, I would find data source relevant to my application and available to my situation and apply your examples to download data and preprocess them. 

Thank you for your help in advance.

**Comment by stefan-jansen** [comment]
Hi Sungyun,

I'm afraid that I cannot share the original data because the provider's licenses generally do not permit this. There's little I can do about this. Could you please be a bit more specific which APIs no longer work so you cannot get the data anymore? 

I hope I clarified in my response to your other issue how to work with the updated environments (see updated [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation) for the current release.

**Comment by sungyunglim** [comment]
Hi Stefan,

Thank you for responding quickly to my messages.
I will follow your new instruction to test the backtest
and regenerate the data set to find out the missing data or broken APIs.
I will get back to you.

Thanks - sungyung

**Comment by stefan-jansen** [comment]
Closing for now, feel free to reopen if you run into further issues.
