### ISSUE TITLE
chap. 6: 01_machine_learning_workflow.ipynb

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#116]
returns error at line:

`correl.r.sort_values().plot.barh();`

`AttributeError: 'DataFrame' object has no attribute 'r'`

Also all Dataframe elements are nan

**Comment by stefan-jansen** [comment]
Sorry, I had not tested this notebook with the new env, I've updated the code to remedy this error.

**Comment by Eeonum** [comment]
on line 
`ax = sns.scatterplot(x='False Positive Rate', y='True Positive Rate', data=roc, size=5, legend=False, ax=axes[0])
`

`TypeError: object of type 'int' has no len()`

**Comment by stefan-jansen** [comment]
I just ran the notebook using the `ml4t` environment provided by the current Docker container and cannot reproduce this error, which suggests that the `roc` input is an integer rather than a `pd.DataFrame`. 

The current version of the notebook creates the `roc` variable as follows in (cell 45):
```python
cols = ['False Positive Rate', 'True Positive Rate', 'threshold']
roc = pd.DataFrame(dict(zip(cols, roc_curve(**pred_scores))))
```
Inspecting the content shows:
```python
roc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   False Positive Rate  67 non-null     float64
 1   True Positive Rate   67 non-null     float64
 2   threshold            67 non-null     float64
dtypes: float64(3)
memory usage: 1.7 KB
```
Could you please let me know what the variable `roc` contains in your case?

**Comment by Eeonum** [comment]
For this example, I am using the ml4t environment provided by you for Mac in the installation directory. Here are the outcomes of roc.info():

first this pops up:
` r = self.sock.recv(1024)
OSError: [Errno 9] Bad file descriptor` which doesn't stop the code from running

and then,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   False Positive Rate  67 non-null     float64
 1   True Positive Rate   67 non-null     float64
 2   threshold            67 non-null     float64
dtypes: float64(3)
memory usage: 1.7 KB
None

**Comment by stefan-jansen** [comment]
The error you mention may be related to multiprocessing during GridSearch and similar routines when using njobs>1, but hard to say without more context.

I don't have an answer why providing the same `DataFrame` as input causes an error. At this point we would have to take a close look at all the versions you have installed and try to recreate your environment on my machine to reproduce the error. Please see my answer to your other issue where I recommend to use the provided Docker image since it has been tested, does not cause this error, and is intended as the default way of running the code. 

Please let me know if you have further questions.

**Comment by Eeonum** [comment]
Thank you. with the current docker (both python and ml4t envs) image I am getting the following error:
`TypeError: type object got multiple values for keyword argument 'text'`

**Comment by stefan-jansen** [comment]
I had updated this to reflect the change to the `matplotlib` interface and the code currently reads: 
```python
f1.plot(ax=axes[2], title='F1 Scores', ylim=(0,1))
axes[2].set_xlabel('Threshold')
axes[2].axvline(best_threshold, lw=1, ls='--', color='k')
axes[2].text(s=f'Max F1 @ {best_threshold:.2f}', x=.5, y=.95)
sns.despine()
fig.tight_layout();
```
Please run `git pull` to obtain the latest version.
