### ISSUE TITLE
chap. 6: 02_mutual_information.ipynb

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#117]
`ValueError: unsupported pickle protocol: 5` at line `with pd.HDFStore('../data/assets.h5') as store:
    data = store['engineered_features']`

All .h5 files and the code have been generated using consistent environment.

**Comment by stefan-jansen** [comment]
I've just rerun this notebook using the `ml4t` environment that I've also used to create the data in the notebook `feature_engineering` in chapter 4 but cannot reproduce this error. Are you using the current Docker image or different environments?

**Comment by Eeonum** [comment]
I am using the ml4t environment provided by you for macosx. I am still getting the same error.

**Comment by stefan-jansen** [comment]
See [here](https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5) for a discussion of how this pickle version mismatch comes about and [here](https://stackoverflow.com/questions/60067953/is-it-possible-to-specify-the-pickle-protocol-when-writing-pandas-to-hdf5) (second answer) for how to modify the pickle version used by HDF5. Typically this is caused by using different Python /pandas versions to write / read.

On environment: I'm very happy to help, but unfortunately, I can only test the notebooks using the Docker image. I've provided the `.yml` for mac/windows for users willing to manage installation independently; they do not contain version numbers and thus don't create deterministic environments. If you repeatedly encounter errors while using your own environment that do not occur with the Docker image, I would strongly recommend using Docker instead; it's pretty straightforward to use and offers a platform-independent runtime environment.

**Comment by life-elixir** [comment]
Perfect. It works now. Thank you Stefan!
