### ISSUE TITLE
Do you have a notebook with the adjusted sharpe ratio?

### ISSUE THREAD

**Issue by BlackArbsCEO** [stefan-jansen/machine-learning-for-trading#119]
Greetings,

Excellent book. I was wondering if you have an example of how to compute and optimize a portfolio for the adjusted sharpe ratio that you mentioned here: 

![image](https://user-images.githubusercontent.com/7452471/110532546-bb276580-80fb-11eb-92b2-6f3fcb039012.png)

I have not found much regarding its use or even description outside of the paper.

**Comment by stefan-jansen** [comment]
Hi, thank you. Unfortunately, I do not have a notebook to demonstrate Lo's adj. SR that takes into account autocorrelation for time-aggregation This might be a good addition for a third edition and should perhaps also be integrated into pyfolio for more accurate performance comparison. 

Optimizing a PF in this regard is probably quite a bit more complicated than using it for ex-post performance measurement and I haven't come across any relevant applications, possibly since the mean-variance approach where it would naturally fit in has become a bit less popular, but haven't given it much thought tbh. Any suggestions for sample applications are welcome!

**Comment by stefan-jansen** [comment]
Closing for now, feel free to reopen if you have further questions or suggestions.
