### ISSUE TITLE
Chapter 22 testing the agent

### ISSUE THREAD

**Issue by ashuarsh** [stefan-jansen/machine-learning-for-trading#139]
Hi,

Going through the Reinforcement Learning chapter and finding it most illuminating! One question - It seems like the part where we test the agent is absent in the Lunar Lander notebook

In q_learning_for_trading notebook, in the end, you allude to the Lunar Lander notebook to see how to test the agent on new data.

Could you add a snippet that shows the testing part in either notebook? Would it be the same as the train except just skipping the experience_replay line?

Another thing I noticed is that in the q_learning_for_trading notebook I see a 2x speed up using GPU vs CPU, whereas this can be 20x speed-up in other places like 19_recurrent_neural_nets/04_multivariate_timeseries - is this expected or we can modify the design in some way to use more GPU?

**Comment by stefan-jansen** [comment]
Hi @ashuarsh, apologies for the late response. Ultimately, the agent just relies on a trained model. To test the agent, you would hold out some data (say the last three years) and then feed those to the agent once it appears to have learned enough. Just like in the 'standard' train- predict steps. I'm sorry but I don't have much time right now to add sample code but will do my best to do so in the future. By the way, I've just set up a [community platform](https://exchange.ml4trading.io/) to facilitate discussions of this nature. It's still early but this could become a good forum to get additional input from others.

The GPU speed up is limited because the network is modest in size and the agent does other things as well that do not benefit from the GPU (but stocks, observe signals, etc). A CNN just runs matrix operations all of the time. For a 'serious' agent, you would probably need a much bigger network and a lot more data (hundreds of stocks..) so the GPU benefit would become more substantial. 

Hope this helps - closing for now, feel free to reopen if you have additional questions on this matter.
