### ISSUE TITLE
Volume used could be wrong

### ISSUE THREAD

**Issue by kecol** [stefan-jansen/machine-learning-for-trading#140]
**Describe the bug**
The notebook below should use dollar volume but it looks like the loaded dataset _top500_ has share volume. So most results generated by the notebook are wrong. 

https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/24_alpha_factor_library/03_101_formulaic_alphas.ipynb

The error comes from thinking that datasest top500 has dollar volume. The notebook below generates this dataset named _top500_ based on the most liquid stocks in a given period. It uses dollar volume to do the filtering. But when saving this selection the notebook saves the original volume (of shares).

https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/24_alpha_factor_library/01_sample_selection.ipynb

I didn't complete my reading of all notebooks so I don't know if the solution is as simple as to replace share volume with dollar_volume on the notebook that makes the selection (01_sample_selection.ipynb). Another solution is to recalculate the dollar volume in the notebook 03_101_formulaic_alphas.ipynb.

PS: there is a bug in this notebook 03_101_formulaic_alphas.ipynb where variable 'h' should be defined as the high price and not the open price. So this mistake generates bad signal values for alphas that require of the high price.

**Comment by stefan-jansen** [comment]
Thank you for identifying the typo that leads to using `open` for instead of `high`, this does indeed affect a number of indicators and I will add a revised version shortly.

Could you please point me to the source that leads you to the conclusion that `volume` should be `dollar volume`? I've based my interpretation o section A2 of [the paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2701346) where the author defines:

## A.2. Input Data
- returns = daily close-to-close returns
- open, close, high, low, volume = standard definitions for daily price and volume data
- vwap = daily volume-weighted average price
- cap = market cap
- adv{d} = average daily dollar volume for the past d days

My understanding of the standard definition of volume is simply volume rather than dollar volume and I believe this is further supported by the separate definition of `adv(d)`. 

Closing for now but feel free to reopen if you have reason to believe my understanding is mistaken.

**Comment by kecol** [comment]
Hi Stefan! Thanks for the really hard work you are doing. Let me tell you that what made me think _volume_ made reference to _dollar volume_ was exactly the definition of ADV in the paper and that many alpha factors use some kind of comparison between volume and ADV.

Definition of ADV:  adv{d} = average daily **dollar volume** for the past d days

For traded volume I think this definition should use **average daily traded volume** instead. Maybe I misunderstand something here. And if it references to dollar volume, then cells 24 and 29 should be updated.

cell 24: `adv20 = data.groupby('ticker').rolling(20).volume.mean().reset_index(0, drop=True)`

cell 29: `adv20 = v.rolling(20).mean()`

**Comment by stefan-jansen** [comment]
I don't think that's right because the paper is very clear that volume is simply volume. It refers to the 'standard definition of daily volume' , which is simply daily volume, not average over an number of days the reader may infer or based on some other variable. Also: why would the author specify a number of days for adv but not for v, leaving it to the reader to assume that volume would be used differently from price variables, but defining volume alongside daily prices?

It's another question whether the indicators perhaps should be using something else than the author suggests but that's entirely up to the reader. Also, keep in mind that this is an old paper and the implementation is really just for illustration; you definitely want to move on from this.

**Comment by kecol** [comment]
Yes! I understand I should look for another indicators. But I wanted to do a fair comparison between "ta-lib" indicators and the "101" indicators, and to be able to do that I should count with the right alphas. That's why I started to pay attention to the variables. I will use traded volume for volume. But in your opinion what does the fifth definition below for adv{d} mean? Does it refers to average daily dollar volume or traded volume?

## A.2. Input Data
- returns = daily close-to-close returns
- open, close, high, low, volume = standard definitions for daily price and volume data
- vwap = daily volume-weighted average price
- cap = market cap
- adv{d} = average daily dollar volume for the past d days

I'm glad I've finally received your book at home. I really appreciate the work you've done. Thank you.

**Comment by stefan-jansen** [comment]
`adv` = avg. daily volume, see quote above. I"m computing this for 20 days as 
```
adv20 = data.groupby('ticker').rolling(20).volume.mean().reset_index(0, drop=True)
```
in the notebook.
