### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by lefig** [stefan-jansen/machine-learning-for-trading#141]
Thank you for an excellent book.

**Comment by stefan-jansen** [comment]
Thank you! Please don't hesitate to get in touch here or via https://exchange.ml4trading.io/ if you have any questions!

**Comment by JeremyWhittaker** [comment]
I agree. I've never read a book as challenging or as enjoyable.

**Comment by stefan-jansen** [comment]
Thank you both! Feel free to let everyone else know via Amazon review :)

**Comment by JeremyWhittaker** [comment]
![image](https://user-images.githubusercontent.com/13750325/114252394-b56eab00-9959-11eb-9312-ec3340b39736.png)
done.

**Comment by JeremyWhittaker** [comment]
Just realized all my typos after posting this. lol

**Comment by JeremyWhittaker** [comment]
How can I immerse myself and surround myself with like people regarding the topics discussed in your book? I feel like I'm on an island and lost and times and a network would be awesome to engage with.

**Comment by stefan-jansen** [comment]
Awesome, much appreciated! I'm afraid there are not that many options since the demise of Quantopian. On one side there's [QuantConnect](https://www.quantconnect.com/) (which I haven't used much because initially there wasn't much ML support plus it's C# based with a Python wrapper that didn't work so well when I tried, but this may have improved. On the other end of the spectrum there is a Reddit group under 'algotrading' or so, but it didn't seem particularly focused when I last checked.

Since this is probably a real gap, and you're not the first to bring it up, I'm going to try and start a community around the readers of the book and the users of my [Manning project](https://www.manning.com/liveproject/algorithmic-trading-with-machine-learning) and anyone else interested: https://exchange.ml4trading.io/. I haven't really announced this yet so it's rather quiet but I'll get back to this before the end of this month.
