### ISSUE TITLE
Setup instructions for initial baseline data construction need improvement

### ISSUE THREAD

**Issue by drsxr** [stefan-jansen/machine-learning-for-trading#168]
I'm trying to work through the book, up to Ch 3 so far but I'm unable to reliably create the specific datasets required for running the examples in the book in their specific formats, mostly because the directory and file structure & names are unclear.  Part of this is because there have been some changes in access and download - that's not your fault, I recognize - but without the same starting files you have, any user will not be able to reliably get into the meat of the book and will just spin their wheels endlessly.  

I'm an intermediate python programmer using both Win10 and Ubuntu20 OS's; for this exercise I'm running miniconda3 in VM mode latest version as of May 2021, no docker.  I downloaded your full repo from github for the ml4T.

I've spent a week on this - it shouldn't be that hard.  

Can you please provide:
1.  An screencapture image of the working directory (/data I belive) with all labeled files and formats so we know what goes where.

Can you please consider:
1.  Re-working and expanding create_datasets.ipynb  so that it includes the above, as well as including the data download and preparation instructions from chapter 2 - the five notebooks that download ITCH data, etc... working forward through the book its hard to know what will be used later and what won't and if something is not added because it is not considered important, you have to go back and re-do it later.
2. I know this is a grey area, but just putting the actual data on your github so that the whole thing can be cloned and downloaded instead of doing all this legwork would be a fantastic help, and really improve the utility of your book.  Given the lack of support of some of this data, I don't think the owners would care.  

I am aware that this is challenging material and will require a great deal of work and adaptation for anyone's individual situation - that is a given.  What I am saying is that there is probably tremendous value in the book - I just can't get to it.

Thanks for considering.

**Comment by stefan-jansen** [comment]
Hi @drsxr, 

I'm sorry to hear you found the material so difficult to work with. Happy to help. Could you please be a bit more specific as to which data you are unable to download? 

- Chapter 2, for instance, does not rely on any of  the notebooks in the `data` directory. Instead, the notebooks in Chapter 2 contain sample code that directly downloads various datasets, most of which are only used there (to illustrate a variety of sources and types). Only the algoseek data appear again in Ch 11 and, for this reason, are stored in the `data/nasdaq100` directory. I did, however, notice that this code would throw an error if that directory did not already exist and just added some code to create it in this case. SEC EDGAR moved to monthly file frequenc after Q3/2020. I've updated the code so it works for the quarterly files, leaving an extension to also download the monthly files as an exercise.
- Chapter 3 only has two web-scraping examples; the seeking-alpha example no longer works since the website added captchas and sample `earnings_call.zip` file is included under [`data`](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/data).

I hope this helps with Ch 2 & 3, but please feel free to reopen and let me know of any other issues you are running into.

Best, Stefan
