### ISSUE TITLE
Error in setting environment on Mac

### ISSUE THREAD

**Issue by yehjames** [stefan-jansen/machine-learning-for-trading#215]
**Describe the bug**
In mac m1 max, I cannot set Conda environment correctly.  I also tried to switch to pyenv but get another hdf5 error....
Does anyone got same issue? Thanks

My OS version: MacOS Monterey version 12.1

**To Reproduce**

```
mamba env update -n ml4t -f installation/ml4t-base.yml
```
Then get this error
```
Looking for: ['arch', 'alphalens-reloaded', 'arviz', 'autopep8', 'beautifulsoup4', 'bokeh', 'catboost', 'colorlover', 'conda', 'empyrical-reloaded', 'ffmpeg', "gensim[version='<4.0']", 'gym', 'gym-box2d', 'html5lib', 'hdbscan', 'ipykernel', 'ipyvolume', 'ipywidgets', 'jupyter', 'jupyter_contrib_nbextensions', 'jupyterlab', 'lightgbm', 'linearmodels', 'lxml', 'matplotlib', 'mplfinance', 'nb_conda', 'nb_conda_kernels', 'nbconvert=5.6.1', 'notebook', 'nltk', 'numpy', 'opencv-python-headless', 'pandas', 'pandas-datareader', 'pillow', 'pip', 'plotly', 'pyarrow', 'pydot', 'pyfolio-reloaded', 'pykalman', 'pyldavis', 'pytorch', 'pymc3', 'pytables', 'python=3.8', 'python-graphviz', 'pywavelets', 'quandl', 'requests', 'scikit-learn', 'scipy', 'scrapy', 'seaborn', 'shap', 'snappy', 'spacy', 'statsmodels', 'sympy', 'ta-lib', 'tensorboard', 'tensorflow', 'tensorflow-datasets', 'termcolor', 'textacy', 'textblob', 'tqdm', 'umap-learn', 'wheel', 'widgetsnbextension', 'wordcloud', 'xgboost', 'xlrd', 'yaml', 'yellowbrick', 'yfinance', 'zipline-reloaded']

Encountered problems while solving:
  - nothing provides requested arch
  - nothing provides requested alphalens-reloaded
  - nothing provides requested catboost
  - nothing provides requested empyrical-reloaded
  - nothing provides requested gensim <4.0
  - nothing provides requested opencv-python-headless
  - nothing provides requested pyfolio-reloaded
  - nothing provides requested ta-lib
  - nothing provides requested textacy
  - nothing provides requested wordcloud
  - nothing provides requested zipline-reloaded
```

**Comment by stefan-jansen** [comment]
Installation on MacOS with M1 is complicated by the fact that many packages do not yet support this architecture at all (e.g. catboost), some only via pip (e.g. zipline-reloaded) others only via conda. 

Unfortunately, I currently don't have an all-around solution for this as this is mostly due to the open-source ecosystem slowly catching up to this fundamental change. You will be able to run most of the material using different pip/conda environments containing the packages available under the respective package manager. Alternatively, there's the Rosetta emulation.

I'll add a remark to the installation instructions highlighting the M1 constraints.

**Comment by stefan-jansen** [comment]
Sorry, what I said above was actually not correct. The packages not (yet) available via `conda` may be available via `pip` (e.g. the various `-reloaded` packages are). Thus, moving those in the environment files into the `pip` section at the end should do the trick.

**Comment by stefan-jansen** [comment]
I'll provide an M1-specific env file in the coming days.

**Comment by bvahdat** [comment]
> Sorry, what I said above was actually not correct. The packages not (yet) available via `conda` may be available via `pip` (e.g. the various `-reloaded` packages are). Thus, moving those in the environment files into the `pip` section at the end should do the trick.

@stefan-jansen unfortunately that doesn't work either as it then fails compiling while trying to build wheels for the following packages moved into the `pip` section as per your suggestion:

```
- gensim<4.0
- zipline-reloaded
- opencv-python-headless
- arch
```

[Attached](https://github.com/user-attachments/files/17179059/log.txt) please find the complete build log where one can see the compilation failing for `gensim<4.0`.

I've just ordered the book and hoped to start coding and see something real on the screen (instead of just on the paper) but right now got blocked. 

<img width="543" alt="Screenshot 2024-09-29 at 13 24 15" src="https://github.com/user-attachments/assets/9472f671-b290-4818-b488-e559e4386d37">

> I'll provide an M1-specific env file in the coming days.

Maybe you've already provided 👆 which I'm missing here?

Another very important point is what you've already mentioned in the documentation:

> Alternatively, there is also an environment file installation/ml4t-base.yml that only contains a list of the required libraries without dependencies; if you use this file instead you will obtain the latest versions - **just be aware that at some point more recent software may become incompatible with the examples.**

So even if creating the virtual environment would work I think there would be tons of errors one would hit while running the notebooks, but hopefully I'm wrong.

Nice would be to see the [deprecated version](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/installation/macosx/ml4t.yml) becoming officially supported having the exact dependency versions. Also [this line with `marianafranco` in it](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/installation/macosx/ml4t.yml#L502) looks a bit strange.

Last but not least, thanks for all the effort you've invested in the book and it's codebase. 🙌

**Comment by stefan-jansen** [comment]
@bvahdat, please do not try to create a single environment and install all packages used by all notebooks. I initially tried to provide this for readers to facilitate installation but have now realized this is a mistake. It's both too complex and unnecessary. For instance, I develop on Ubuntu using pip, and the combination of packages that I used may not even be available on MacOS/Windows using pip or conda. This happens in open-source software.

Four years later, I think the best and simplest approach is that you simply install the packages that a notebook you want to run imports. In many cases, this is a small number of very common libraries, and you may be able to re-use this environment, perhaps by installing yet another package. In other cases, things may be more complicated - TensorFlow may not yet support the Python version you started with, etc. Then, just create a new environment. 

If you run a newer version than I used when creating things, you may run into errors when a library changes its API. In this case, just update the code accordingly or downgrade the version; the docs will usually say when the changes took place. It's an essential skill, usually reasonably straightforward, and allows you to use current versions. If you find the code practically relevant, you'd want to update it anyway. If you're not interested in actually using it, running it yourself instead of just looking at critical outputs (often in the notebooks or the book itself) would seem to be of limited value.

For the 3rd edition, I'll use Docker so everyone can also run the code on Ubuntu. I've spent days coming up with installation instructions that would work for everyone, and it has turned out to be much more complicated than expected (every system is different, conda has its issues, things keep changing over the years, skill sets vary widely).

Hope this helps.

**Comment by bvahdat** [comment]
Thanks @stefan-jansen for your suggestion.

I think the main unresolved problem still remains, which is not being able to install some dependencies such as `zipline-reloaded` on ARM based macOS hardware, at least very difficult to do so if at all, e.g. see https://github.com/stefan-jansen/zipline-reloaded/issues/1

For now the cheapest and easiest solution for me was to use my old 2011 MacBookPro laptop where installing dependencies worked out:

```
conda env create -f installation/macosx/ml4t.yml
```

**Comment by stefan-jansen** [comment]
@bvahdat have you tried:

<img width="533" alt="Screenshot 2024-09-30 at 5 14 59 PM" src="https://github.com/user-attachments/assets/c638aeee-98de-40a7-86df-b74ba329790d">

There are no updated conda packages because the dependencies have not updated theirs.

Hope this helps.

**Comment by bvahdat** [comment]
Thanks @stefan-jansen that worked 👍
