### ISSUE TITLE
Chapter 4: 06_performance_eval_alphalens.ipynb

### ISSUE THREAD

**Issue by Quantuary** [stefan-jansen/machine-learning-for-trading#245]
**Describe the bug**
1. 
The `Mean Period Wise Return` chart produces by the `create summary_tear_sheet` is different from the same chart produces using output from `mean_return_by_quantile`. e.g. 10D shows a wider spread in the book version, using `mean_return_by_quantile`. However the tear sheet method shows 5D is superior.
Can anyone shed some light please?

tear sheet method:
![Screenshot from 2022-05-22 13-44-02](https://user-images.githubusercontent.com/43050453/169677501-ddb8bcd6-2032-482a-b37f-4ecc1ab3077d.png)

vs

`mean_return_by_quantile` methods:
![Screenshot from 2022-05-22 13-43-46](https://user-images.githubusercontent.com/43050453/169677499-25207707-41d4-4300-afcc-624cc8f91006.png)

**Comment by stefan-jansen** [comment]
Could this be due to different time frames or other changes to the setup? The tear sheet calls that function so I doubt the output would differ unless the input changes. 

Please keep in mind that the code in the notebook is not always 100% identical to what's used to generate the charts in the book, not least because I've sometimes updated examples in response to reader questions or suggestions.

Closing for now, please feel free to reopen if you have further questions.
