### ISSUE TITLE
Stooq hd5 format can not be created 

### ISSUE THREAD

**Issue by schullino1** [stefan-jansen/machine-learning-for-trading#264]
ValueError: No objects to concatenate

This error occurs if it try to generate the file even though I have dowloaded the files in the correct directory. I even changed the Index names in the Files from <TICKER> and <NAME> to ticker and name but still this mistake occurs. The problem is there are to many txt files with probably different Index names <TICKER> ....

**Comment by schullino1** [comment]
in [8] line 181 
  prices = (pd.concat(prices, ignore_index=True)
              .rename(columns=str.lower)
              .set_index(['ticker', date_label])
              .apply(lambda x: pd.to_numeric(x, errors='coerce')))

**Comment by stefan-jansen** [comment]
If there are not objects to concatenate this means that the files are not being read, probably because the names have changed since publication. Please keep in mind that the risk of using free data is that breaking changes can occur at any time. I would recommend comparing the names of downloaded files with what the code is expecting.
