### ISSUE TITLE
TypeError: download() got multiple values for argument 'start' when using pandas_datareader.data

### ISSUE THREAD

**Issue by edward1019** [stefan-jansen/machine-learning-for-trading#313]
**Describe the bug**
I got this error(per title) sometimes when running pandas_datareader.data to download following the 01_pandas_datareader_demo.ipynb

**Screenshots**

**Environment**
![image](https://github.com/stefan-jansen/machine-learning-for-trading/assets/7684883/2e4aad2f-91df-4788-b15e-5cdbfc67fbad)

- OS: [e.g. MacOSX, Windows, Ubuntu]
 - Version [e.g. Big Sur, 11.7.8]

**Comment by stefan-jansen** [comment]
The error suggests one of your arguments is interpreted as 'start', which implies that it's the first or second positional argument. I would expect this to work according to their docs but since it doesn't, just use kwargs in all cases. 

If you run into issues like these, it's usually most helpful to take a look at the [library's code](https://github.com/pydata/pandas-datareader/blob/a1cf7a20fe03dd63e930fa5ca1311a57897c9ddd/pandas_datareader/data.py#L473).
