### ISSUE TITLE
Downloading from NASDAQ server in create_datasets.ipynb not working

### ISSUE THREAD

**Issue by sgjohnson1981** [stefan-jansen/machine-learning-for-trading#63]
The cell below in the create_datasets notebook is not working. It doesn't throw any kind of error. It just hangs and does nothing. As far as I can tell, you're using the request and pandas library to iterate through the exchanges with a for loop. I can't see how this would work. I can't find anything in the format() documentation about the ability to pass in iterations of a loop rather than just a variable.

    url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
    exchanges = ['NASDAQ', 'AMEX', 'NYSE']
    df = pd.concat([pd.read_csv(url.format(ex)) for ex in exchanges]).dropna(how='all', axis=1)
    df = df.rename(columns=str.lower).set_index('symbol').drop('summary quote', axis=1)
    df = df[~df.index.duplicated()]
    print(df.info())

**Comment by stefan-jansen** [comment]
Hi @sgjohnson1981, looks like NASDAQ is not blocking automatic downloads. The urls still work for manual downloads - `.format()` works just fine in a loop. You can just run in a notebook and click on the urls to have your browser download the files.

```python
url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
exchanges = ['NASDAQ', 'AMEX', 'NYSE']
for exchange in exchanges:
    print(url.format(exchange))
```
I'll update the `create_datasets` notebook accordingly in the coming days.

**Comment by sgjohnson1981** [comment]
Thank you.

Also, how did you ascertain they were no longer allowing this?

**Comment by stefan-jansen** [comment]
I'm assuming. The url still works for downloads and the `.read_csv()` download also worked the last time I tested a few months ago. So, I'm concluding they are no longer permitting automated downloads as they used to.

**Comment by N2Network** [comment]
Was hoping you could confirm this code would have the same effect. My coding is not strong but I think it gets the same result?

df_nasdaq = pd.read_csv("nasdaq.csv") 
df_amex = pd.read_csv("amex.csv") 
df_nyse = pd.read_csv("nyse.csv") 

df = pd.concat([df_nasdaq,df_amex,df_nyse]).dropna(how='all', axis=1)
df = df.rename(columns=str.lower).set_index('symbol')
df = df[~df.index.duplicated()]
print(df.info())

**Comment by stefan-jansen** [comment]
Looks good. Did anything go wrong? 

If `df.head()` doesn't give you enough confidence you can also save to csv and take a look.

**Comment by N2Network** [comment]
Market cap is already formatted correctly. So I believe the rest of the code can be commented out. Other than that no issues. I'm sure there is a way to loop or make this prettier but like I said my coding skills are not that strong. 

![image](https://user-images.githubusercontent.com/13750325/108564300-1bc33f80-72c0-11eb-9e4e-35b00ddbb8a3.png)

url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
exchanges = ['NASDAQ', 'AMEX', 'NYSE']
for exchange in exchanges:
    print(url.format(exchange))
# download csv files into directory

# url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
# exchanges = ['NASDAQ', 'AMEX', 'NYSE']
# df = pd.concat([pd.read_csv(url.format(ex)) for ex in exchanges]).dropna(how='all', axis=1)
# df = df.rename(columns=str.lower).set_index('symbol').drop('summary quote', axis=1)
# df = df[~df.index.duplicated()]
# print(df.info()) 

df_nasdaq = pd.read_csv("nasdaq.csv") 
df_amex = pd.read_csv("amex.csv") 
df_nyse = pd.read_csv("nyse.csv") 

df = pd.concat([df_nasdaq,df_amex,df_nyse]).dropna(how='all', axis=1)
df = df.rename(columns=str.lower).set_index('symbol')
df = df[~df.index.duplicated()]
print(df.info()) 

# unecessary code because format is not the same.
# df = df.rename(columns={'market cap': 'marketcap'})
# mcap = df[['marketcap']].dropna()
# mcap['suffix'] = mcap.marketcap.str[-1]
# mcap.suffix.value_counts()


# unecessary code because format is not the same.
# mcap = mcap[mcap.suffix.str.endswith(('B', 'M'))]
# mcap.marketcap = pd.to_numeric(mcap.marketcap.str[1:-1])
# mcaps = {'M': 1e6, 'B': 1e9}
# for symbol, factor in mcaps.items():
#     mcap.loc[mcap.suffix == symbol, 'marketcap'] *= factor
# mcap.info()

# df['marketcap'] = mcap.marketcap
# df.marketcap.describe(percentiles=np.arange(.1, 1, .1).round(1)).apply(lambda x: f'{int(x):,d}')

**Comment by zxweed** [comment]
manual download was disabled also. For example - the link https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NASDAQ&render=download forwards to homepage now
