### ISSUE TITLE
issues on ml4t-zipline - mac osx catalina

### ISSUE THREAD

**Issue by luisvelo** [stefan-jansen/machine-learning-for-trading#71]
Hi Stefan

My Docker runs, I was able to do also the zipline ingest. All these commands in terminal do work well
_cd ~/Library/Containers/com.docker.docker/Data/vms/0/
docker start -a -i ml4t
conda activate ml4t-zipline_

I can launch jupyter both ways
_jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
jupyter lab --ip 0.0.0.0 --no-browser --allow-root_

Then I go to below link:
https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/04_single_factor_zipline.ipynb

Almost all code works well, like %matplotlib inline & import matplotlib.pyplot as plt

And all the code listed below "_class MeanReversion(CustomFactor):_" also works well

But I receive the errors on the below sentence (ingestion went well, did that a couple of days ago):
_%%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle_
UsageError: %%zipline is a cell magic, but the cell body is empty. Did you mean the line magic %zipline (single %)?

And there is no output like the table listed at the end of your link. And I just see 3 nb extensions, I'm not able to find the zipline nbextension on jupyter (if that is the problem)

In any case, I'm not (now) very interested in Zipline, I'm more interested on factors, Alphalens and etc. 
1- Can you kindly post single_factor.pickle in the data directory?
2- Whenever you have time (and if it makes sense/is possible), if you can eliminate the dependency with Quantopian on below it will be appreciated:
https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/05_multiple_factors_quantopian_research.ipynb
https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/07_factor_library_quantopian.ipynb

I wanted to signal you also this fork on zipline
https://github.com/shlomikushchi/zipline-trader

Thanks again for your help & support

**Comment by luisvelo** [comment]
import seaborn as sns
I was able to fix it doing a conda installation of Seaborn

But %%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle is giving me the same error

**Comment by luisvelo** [comment]
I just see 3 nb extensions, I'm not able to find the zipline nbextension on jupyter

**Comment by stefan-jansen** [comment]
The error says that the cell body is empty. However, there should be the code for your algorithm - in the same cell that starts with `%%zipline`. See [here](https://www.zipline.io/beginner-tutorial.html#working-example-dual-moving-average-cross-over) for the Zipline tutorial that illustrates the result. 

You should be able to run the code exactly as shown on [GitHub](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/04_single_factor_zipline.ipynb) and create the file.

The two notebooks you mention are unfortunately no longer operational. [This one](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/05_multiple_factors_quantopian_research.ipynb) can't be ported since it relies on Quantopian data that are no longer available. The other notebook can probably be adapted using Zipline's Pipeline functionality, perhaps I'll take a stab should there be a 3rd edition.

**Comment by luisvelo** [comment]
Hi Stefan, thanks again

1. I did the buyapple script you pointed me to, thanks. It works
2. When running the script marked below I got the message marked in the link https://github.com/stefan-jansen/machine-learning-for-trading/issues/21 . But then I'm not able to find the SQLLite db. Where it should be located? How should I access it? is inside the Docker, should I have the Docker running, isn't it?

_https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/04_single_factor_zipline.ipynb_

3. If you are able to post the file 'single_factor.pickle' on the data directory, that will be appreciated

Thanks in advance,
Luis
