### ISSUE TITLE
Chapter 05. 'DataFrame' object has no attribute 'close'

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#74]
when I run the below code, I got a 'DataFrame' object that has no attribute 'close' message

> with pd.HDFStore(HDF_PATH) as store:
>  benchmark_rets = store['sp500/prices'].close.pct_change()
> benchmark_rets.name = 'S&P500'
> benchmark_rets = benchmark_rets.tz_localize('UTC').filter(returns.index[0])
> benchmark_rets.tail()

how can I fix it?

**Comment by stefan-jansen** [comment]
The error occurs because `benchmark_rets` has no `close` column, which it should have if downloaded as described in the [instructions](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/data/create_datasets.ipynb) (where we name it `'sp500/fred'`, so perhaps you sourced the data from elsewhere): 

```
df = web.DataReader(name='SP500', data_source='fred', start=2009).squeeze().to_frame('close')
print(df.info())
with pd.HDFStore(DATA_STORE) as store:
    store.put('sp500/fred', df)
```
Please run
```
with pd.HDFStore(HDF_PATH) as store:
    benchmark_rets = store['sp500/prices']
print(benchmark_rets.info())
```
to verify what's in your DataFrame and either rename the columns or recreate this dataset as outlined above. Please be aware that stooq no longer permits automatic downloads, if you are using their service you'll have to download the data from their site manually.
