### ISSUE TITLE
issue with SQL lite on 04_single_factor_zipline.ipynb

### ISSUE THREAD

**Issue by luisvelo** [stefan-jansen/machine-learning-for-trading#75]
Hi Stefan

When running the script (_https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/04_single_factor_zipline.ipynb_) I got the message detailed here (_https://github.com/stefan-jansen/machine-learning-for-trading/issues/21_) 

I'm not able to find the SQLLite. Where it should be located? How should I access it? Is inside the Docker, should I have the Docker running, isn't it?

Also, if you are able to post the file 'single_factor.pickle' on the data directory, that will be appreciated. I will be able to move forward and go deeper into Alphalens as from the below link
_https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/06_performance_eval_alphalens.ipynb_

Thanks

**Comment by stefan-jansen** [comment]
The [instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation#ingesting-zipline-data) link to the SQLite Browser which is a client you install on your host system to open the database and enter the country code in the tables as described. They also reference a Quantopian GitHub issue that explains the problem. 

Here's a [tutorial](https://www.howtogeek.com/704243/how-to-use-db-browser-for-sqlite-on-linux/). This should be fairly straightforward to do since it has a GUI.

Happy to add the `single_factor.pickle`. I trust you'll be able to fix the error though as just outlined and I'd definitely encourage you try it; if you can't run the backtests you're probably going to get a lot less out of the book.

Just reopen if you run into additional issues on this matter.
