### ISSUE TITLE
Quantopian Shut Down ?

### ISSUE THREAD

**Issue by Dojoon-Park** [stefan-jansen/machine-learning-for-trading#94]
Dear

It seems that Quantopian shut down end of 2020.
I have issue to import run_pipeline from Quantopian.Research.

Is there any alternatives or fixes of the existing codes?

Many thanks
Dojoon

**Comment by stefan-jansen** [comment]
I'm afraid the notebooks [factor_library_quantopian](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/07_factor_library_quantopian.ipynb) in Chapter 4 and [ml4t_quantopian](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/08_ml4t_workflow/04_ml4t_workflow_with_zipline/04_ml4t_quantopian.ipynb) in chapter 8 no longer work because they rely both on data and libraries provided by Quantopian's platform. 

That's of course a shame, but I hope the remaining examples, such as [common_alpha_factors](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/24_alpha_factor_library/02_common_alpha_factors.ipynb) in the appendix and [ml4t_with_zipline](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/08_ml4t_workflow/04_ml4t_workflow_with_zipline/03_ml4t_with_zipline.ipynb) are helpful as they demonstrate similar functionality.
